//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrowdDj.BL.Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyGuests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PartyGuests()
        {
            this.PartyTweets = new HashSet<PartyTweets>();
            this.Tracks = new HashSet<Tracks>();
        }
    
        public int Id { get; set; }
        public int PartyCode { get; set; }
        public int GuestId { get; set; }
        public int PartyId { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual Guests Guests { get; set; }
        public virtual Parties Parties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartyTweets> PartyTweets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tracks> Tracks { get; set; }
    }
}
